import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // `sharp` is a native-binary image lib (used by perception.ts to normalize/downscale generated images,
  // incl. decoding webp/avif). Keep it external so it loads from node_modules with the right platform
  // binary at runtime instead of being bundled (the standard way to use sharp in a route handler).
  serverExternalPackages: ["sharp"],
  // The registry lives in the server-only data/registry/ dir (not public/). Bundle those JSON files
  // into EVERY route's serverless function trace so server handlers can fs-read them at runtime on
  // Vercel. Keys are picomatch globs matched against the route path; a plain "/*" does NOT cross
  // slashes (so it missed the MCP route → /mcp threw `ENOENT data/registry/index.json` in prod).
  // The globstar "/**" matches all route paths at any depth (verified with picomatch).
  outputFileTracingIncludes: {
    // data/registry/** = the catalog; data/mcp-apps/** = the bundled ui:// run-viewer HTML (MCP Apps,
    // regenerated by `prebuild`). Both must ride in the /mcp route's serverless trace for runtime fs reads.
    // Only the runtime-served registry files (registry.ts reads index.json + by-subcat/<slug>.json).
    // NOT data/registry/**/*.json — that also dragged the QA test scratch (qa-artifacts/qa-results/
    // qa-batch-*) into every function bundle. meta.json kept (tiny) for safety.
    "/**": ["./data/registry/index.json", "./data/registry/meta.json", "./data/registry/by-subcat/**/*.json", "./data/bundles/**/*.json", "./data/mcp-apps/**", "./data/apify/*.json"],
    // The /skill route fs-reads the getting-started guide it serves at masterkey.sh/skill.
    "/skill": ["./data/skill/GETTING_STARTED.md"],
  },
  // Local-only registry scratch (discovery sweeps, QA probe artifacts) is gitignored and never
  // read at runtime, but it sits right next to index.json/by-subcat/ under data/registry/, and a
  // dynamic readFileSync(join(DIR, "by-subcat", `${slug}.json`)) in registry.ts makes file tracing
  // fall back to sweeping the whole data/registry/ tree — dragging ~570MB of local scratch into
  // EVERY route's serverless function and blowing the 250MB uncompressed function-size limit.
  // Exclude it explicitly so a deploy is never at the mercy of what happens to be on the build
  // machine's disk under data/registry/.
  outputFileTracingExcludes: {
    "/**": [
      "./data/registry/discovery/**",
      "./data/registry/qa-artifacts/**",
      "./data/registry/qa-results/**",
      "./data/registry/qa-batch-*",
      "./data/registry/*.jsonl",
    ],
  },
};

export default nextConfig;
