// The discovery driver: category → subcategory → search keywords.
// Seeded from the catalog taxonomy; x402-search expands queries server-side, so 1–3 good seeds per subcat suffice.

export const CATEGORIES = [
  { slug: "media", name: "Media", subcategories: [
    { slug: "image-generation", name: "Image Generation", queries: ["image generation", "text to image", "image model", "midjourney", "recraft", "leonardo ai", "fal.ai", "ideogram", "krea", "prodia", "together ai image"] },
    { slug: "video-generation", name: "Video Generation", queries: ["video generation", "text to video", "ai video", "runway", "kling", "pika", "luma dream machine", "hailuo", "minimax video", "synthesia"] },
    { slug: "voice-tts", name: "Voice & Text-to-Speech", queries: ["text to speech", "tts", "voice cloning", "speech synthesis", "elevenlabs", "voice generation", "cartesia", "playht", "lmnt", "murf", "deepgram aura", "inworld tts", "amazon polly", "azure tts", "wellsaid"] },
    { slug: "speech-to-text", name: "Speech-to-Text", queries: ["speech to text", "stt", "transcription", "audio transcription", "whisper", "transcribe audio", "deepgram", "assemblyai", "gladia", "speechmatics", "rev ai"] },
    { slug: "avatars-digital-humans", name: "Avatars & Digital Humans", queries: ["ai avatar", "digital human", "talking avatar", "talking head video", "heygen", "avatar video", "d-id", "synthesia", "arcads", "colossyan", "deepbrain ai"] },
    { slug: "lip-sync", name: "Lip Sync", queries: ["lip sync", "lipsync", "lip sync video", "sync labs", "talking video dub", "lipsync.com", "sync.so"] },
    { slug: "music-generation", name: "Music Generation", queries: ["music generation", "ai music", "text to music", "suno", "song generation", "stable audio", "riffusion"] },
    { slug: "sound-effects-audio", name: "Sound Effects & Audio", queries: ["sound effects", "audio generation", "sfx", "sound generation", "foley audio", "mirelo", "dolby.io"] },
  ]},
  { slug: "infrastructure", name: "Infrastructure", subcategories: [
    { slug: "app-hosting-paas", name: "App Hosting & PaaS", queries: ["app hosting", "deploy app", "paas"] },
    { slug: "sandbox-environments", name: "Sandbox Environments", queries: ["code sandbox", "run code", "execute code sandbox"] },
    { slug: "vm-cloud-providers", name: "VM & Cloud Providers", queries: ["virtual machine", "cloud compute vm"] },
    { slug: "serverless-edge", name: "Serverless & Edge", queries: ["serverless function", "edge function"] },
    { slug: "cdn-edge-networks", name: "CDN & Edge Networks", queries: ["cdn", "content delivery"] },
    { slug: "dns-domain-management", name: "DNS & Domain Management", queries: ["domain registration", "dns", "register domain"] },
    { slug: "container-orchestration", name: "Container & Orchestration", queries: ["container", "kubernetes"] },
  ]},
  { slug: "communication", name: "Communication", subcategories: [
    { slug: "email", name: "Email", queries: ["send email", "email api", "transactional email"] },
    { slug: "sms-phone", name: "SMS & Phone", queries: ["send sms", "phone call api", "voice call"] },
    { slug: "live-chat-messaging", name: "Live Chat & Messaging", queries: ["chat messaging api", "live chat"] },
    { slug: "push-notifications", name: "Push Notifications", queries: ["push notifications"] },
    { slug: "video-voice-calls", name: "Video & Voice Calls", queries: ["video call api", "voice call api"] },
    { slug: "in-app-notifications", name: "In-App Notifications", queries: ["in app notifications"] },
  ]},
  { slug: "data-intelligence", name: "Data & Intelligence", subcategories: [
    { slug: "weather", name: "Weather", queries: ["weather api", "weather forecast", "openweathermap", "weatherapi", "tomorrow.io", "open-meteo", "xweather"] },
    { slug: "flight-aviation", name: "Flight & Aviation", queries: ["flight data", "aviation api", "flight tracking", "aviationstack", "flightradar24", "aerodatabox", "cirium"] },
    { slug: "traffic-transportation", name: "Traffic & Transportation", queries: ["traffic data", "transit api"] },
    { slug: "maps-geolocation", name: "Maps & Geolocation", queries: ["maps api", "geocoding", "mapbox", "nominatim openstreetmap", "mapquest", "locationiq"] },
    { slug: "stocks-financial-data", name: "Stocks & Financial Data", queries: ["stock data", "financial market data", "polygon.io stocks", "finnhub", "financial modeling prep", "iex cloud", "eodhd", "twelve data"] },
    { slug: "crypto-blockchain-data", name: "Crypto & Blockchain Data", queries: ["crypto price data", "blockchain data", "onchain data", "moralis", "glassnode", "chainlink data feed", "blockchair"] },
    { slug: "trends-sentiment", name: "Trends & Sentiment", queries: ["trends data", "sentiment analysis", "brandwatch", "meltwater", "lunarcrush"] },
    { slug: "seo-keywords", name: "SEO & Keywords", queries: ["seo keywords", "keyword data", "dataforseo", "se ranking", "ahrefs", "semrush", "moz seo", "serpapi"] },
    { slug: "social-media-data", name: "Social Media Data", queries: ["social media data", "twitter data", "tiktok data", "twitterapi.io", "data365", "bright data", "youtube data api", "reddit api"] },
    { slug: "news-media", name: "News & Media", queries: ["news api", "news articles", "gnews", "mediastack", "newscatcher"] },
    { slug: "company-people-data", name: "Company & People Data", queries: ["company data api", "people data enrichment", "contact enrichment", "lead enrichment", "apollo.io", "hunter.io email", "clearbit", "people data labs", "crunchbase", "zoominfo"] },
  ]},
  { slug: "web-automation", name: "Web Automation", subcategories: [
    { slug: "web-scraping", name: "Web Scraping", queries: ["web scraping", "scrape website", "scrapingbee", "scrapfly", "bright data", "oxylabs"] },
    { slug: "web-crawling", name: "Web Crawling", queries: ["web crawling", "crawl site", "spider cloud crawler"] },
    { slug: "headless-browsers", name: "Headless Browsers", queries: ["headless browser", "browser automation"] },
    { slug: "screenshot-rendering", name: "Screenshot & Rendering", queries: ["website screenshot", "render html", "urlbox", "apiflash", "microlink"] },
    { slug: "browser-automation-testing", name: "Browser Automation & Testing", queries: ["browser testing", "automated testing", "browserstack", "lambdatest"] },
  ]},
  { slug: "ai-ml", name: "AI & Machine Learning", subcategories: [
    { slug: "llm-chat-apis", name: "LLM & Chat APIs", queries: ["llm chat", "chat completion", "language model"] },
    { slug: "ai-model-hosting-inference", name: "AI Model Hosting & Inference", queries: ["model inference", "ai inference api"] },
    { slug: "embeddings-vector", name: "Embeddings & Vector", queries: ["text embeddings", "embedding model"] },
    { slug: "vision-image-recognition", name: "Vision & Image Recognition", queries: ["image recognition", "computer vision api"] },
    { slug: "nlp-text-analysis", name: "NLP & Text Analysis", queries: ["nlp text analysis", "entity extraction"] },
    { slug: "translation", name: "Translation", queries: ["translation api", "translate text"] },
    { slug: "content-moderation", name: "Content Moderation", queries: ["content moderation", "moderation api"] },
  ]},
  { slug: "auth-identity", name: "Auth & Identity", subcategories: [
    { slug: "authentication-user-management", name: "Authentication & User Management", queries: ["authentication api", "user management"] },
    { slug: "identity-verification-kyc", name: "Identity Verification & KYC", queries: ["identity verification", "kyc api"] },
    { slug: "oauth-sso-providers", name: "OAuth & SSO Providers", queries: ["oauth sso", "single sign on"] },
  ]},
  { slug: "payments-billing", name: "Payments & Billing", subcategories: [
    { slug: "payment-processing", name: "Payment Processing", queries: ["payment processing", "accept payments"] },
    { slug: "crypto-web3-payments", name: "Crypto & Web3 Payments", queries: ["crypto payments", "web3 payments", "stablecoin payment"] },
    { slug: "billing-subscriptions", name: "Billing & Subscriptions", queries: ["billing subscriptions", "subscription api"] },
    { slug: "invoicing", name: "Invoicing", queries: ["invoicing api", "create invoice"] },
  ]},
  { slug: "database-storage", name: "Database & Storage", subcategories: [
    { slug: "relational-databases", name: "Relational Databases", queries: ["postgres database api", "sql database"] },
    { slug: "nosql-document-databases", name: "NoSQL & Document Databases", queries: ["nosql database", "document database"] },
    { slug: "realtime-sync-databases", name: "Realtime & Sync Databases", queries: ["realtime database", "sync database"] },
    { slug: "key-value-caching", name: "Key-Value & Caching", queries: ["key value store", "redis cache"] },
    { slug: "object-file-storage", name: "Object & File Storage", queries: ["object storage", "file storage api", "upload file"] },
    { slug: "decentralized-ipfs", name: "Decentralized & IPFS", queries: ["ipfs storage", "decentralized storage"] },
    { slug: "vector-databases", name: "Vector Databases", queries: ["vector database", "vector search"] },
  ]},
  { slug: "devtools-observability", name: "DevTools & Observability", subcategories: [
    { slug: "error-tracking-monitoring", name: "Error Tracking & Monitoring", queries: ["error tracking", "error monitoring"] },
    { slug: "logging", name: "Logging", queries: ["logging api", "log management"] },
    { slug: "apm-performance-monitoring", name: "APM & Performance Monitoring", queries: ["apm performance monitoring"] },
    { slug: "testing-qa", name: "Testing & QA", queries: ["testing api", "qa automation"] },
    { slug: "feature-flags", name: "Feature Flags", queries: ["feature flags"] },
    { slug: "uptime-status-pages", name: "Uptime & Status Pages", queries: ["uptime monitoring", "status page"] },
  ]},
  { slug: "search", name: "Search", subcategories: [
    { slug: "web-search-apis", name: "Web Search APIs", queries: ["web search api", "search the web"] },
    { slug: "serp-seo-apis", name: "SERP & SEO APIs", queries: ["serp api", "google search results", "serpapi", "dataforseo"] },
    { slug: "ai-semantic-search", name: "AI & Semantic Search", queries: ["semantic search", "ai search", "exa search"] },
    { slug: "site-search-internal", name: "Site Search (Internal)", queries: ["site search api", "algolia"] },
  ]},
  { slug: "document-content", name: "Document & Content", subcategories: [
    { slug: "pdf-generation-processing", name: "PDF Generation & Processing", queries: ["pdf generation", "html to pdf"] },
    { slug: "ocr-document-extraction", name: "OCR & Document Extraction", queries: ["ocr", "document extraction"] },
    { slug: "e-signature", name: "E-Signature", queries: ["e signature api", "esign"] },
    { slug: "headless-cms", name: "Headless CMS", queries: ["headless cms"] },
    { slug: "rich-text-collaboration", name: "Rich Text & Collaboration", queries: ["collaborative editing", "rich text api"] },
  ]},
  { slug: "image-video-processing", name: "Image & Video Processing", subcategories: [
    { slug: "background-removal", name: "Background Removal", queries: ["background removal", "remove background"] },
    { slug: "image-editing-manipulation", name: "Image Editing & Manipulation", queries: ["image editing", "image manipulation", "image to image", "inpainting", "image upscale", "edit image"] },
    { slug: "video-editing-transcoding", name: "Video Editing & Transcoding", queries: ["video transcoding", "video editing api", "ffmpeg", "video convert", "video merge", "video processing"] },
    { slug: "transcription-subtitles", name: "Transcription & Subtitles", queries: ["subtitles", "captioning", "video subtitles", "srt generation", "video to subtitle"] },
    { slug: "image-video-cdn", name: "Image & Video CDN", queries: ["image cdn", "video cdn", "image optimization"] },
  ]},
  { slug: "scheduling-calendars", name: "Scheduling & Calendars", subcategories: [
    { slug: "scheduling-booking", name: "Scheduling & Booking", queries: ["scheduling api", "booking api"] },
    { slug: "cron-job-scheduling", name: "Cron & Job Scheduling", queries: ["cron jobs", "scheduled jobs"] },
    { slug: "queue-background-jobs", name: "Queue & Background Jobs", queries: ["job queue", "background jobs"] },
  ]},
  { slug: "analytics-bi", name: "Analytics & BI", subcategories: [
    { slug: "product-analytics", name: "Product Analytics", queries: ["product analytics"] },
    { slug: "web-analytics", name: "Web Analytics", queries: ["web analytics"] },
    { slug: "session-replay-heatmaps", name: "Session Replay & Heatmaps", queries: ["session replay", "heatmaps"] },
    { slug: "ab-testing-experimentation", name: "A/B Testing & Experimentation", queries: ["ab testing", "experimentation"] },
  ]},
  { slug: "ecommerce", name: "eCommerce", subcategories: [
    { slug: "storefront-commerce-apis", name: "Storefront & Commerce APIs", queries: ["ecommerce api", "storefront api", "buy product"] },
    { slug: "shipping-logistics", name: "Shipping & Logistics", queries: ["shipping api", "logistics tracking"] },
    { slug: "tax-compliance", name: "Tax & Compliance", queries: ["tax calculation api", "sales tax", "vat", "tax rate", "tax api", "compliance check"] },
  ]},
  { slug: "security", name: "Security", subcategories: [
    { slug: "captcha-bot-protection", name: "CAPTCHA & Bot Protection", queries: ["captcha", "bot protection"] },
    { slug: "waf-ddos-protection", name: "WAF & DDoS Protection", queries: ["waf", "ddos protection"] },
    { slug: "secrets-management", name: "Secrets Management", queries: ["secrets management"] },
    { slug: "vulnerability-scanning", name: "Vulnerability Scanning", queries: ["vulnerability scanning", "security scan"] },
  ]},
  { slug: "forms-surveys", name: "Forms & Surveys", subcategories: [
    { slug: "form-builders-apis", name: "Form Builders & APIs", queries: ["form builder api", "forms api"] },
    { slug: "survey-feedback", name: "Survey & Feedback", queries: ["survey api", "feedback api"] },
  ]},
  { slug: "maps-location", name: "Maps & Location", subcategories: [
    { slug: "mapping-geocoding", name: "Mapping & Geocoding", queries: ["geocoding api", "mapping api"] },
    { slug: "address-validation", name: "Address Validation", queries: ["address validation", "address verification"] },
    { slug: "ip-geolocation", name: "IP Geolocation", queries: ["ip geolocation", "ip lookup"] },
  ]},
];

export const CATEGORY_BY_SLUG = Object.fromEntries(CATEGORIES.map((c) => [c.slug, c]));
