// Masterkey × MCP Apps — the ui:// run-viewer resource (MCP_APPS_SPEC.md §5).
//
// Serves the esbuild-bundled guest (data/mcp-apps/run-viewer.html) as a content-hashed
// `ui://masterkey/run-viewer@<hash>` resource. The hash is derived AT RUNTIME from the served bytes,
// so the resource URI and the tool's `_meta.ui.resourceUri` (which calls getRunViewerUri()) can never
// drift from the actual content — important because hosts preload/cache `ui://` resources by URI.
//
// Registration is flag-gated by the CALLER (route.ts only calls this when isMcpAppsEnabled()).

import { readFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { join } from "node:path";
import { registerAppResource, getUiCapability, RESOURCE_MIME_TYPE, RESOURCE_URI_META_KEY } from "@modelcontextprotocol/ext-apps/server";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { isMcpAppsEnabled } from "@/lib/mcp/apps/flag";

// Mirror the registry loader's path strategy (src/lib/registry.ts): read from data/ under cwd. Bundled
// into the serverless trace via next.config.ts outputFileTracingIncludes (regenerated by `prebuild`).
const HTML_PATH = join(process.cwd(), "data", "mcp-apps", "run-viewer.html");

// CSP (§5.3): the viewer consumes Blob-mirrored media, so the image/video/audio origin allowlist
// collapses to ONE stable origin. connectDomains is empty in display-only v1 (no fetch/XHR/beacon).
const BLOB_ORIGIN = "https://*.public.blob.vercel-storage.com";

let cache: { html: string; uri: string } | null = null;

function load(): { html: string; uri: string } {
  if (cache) return cache;
  const html = readFileSync(HTML_PATH, "utf8");
  const hash = createHash("sha256").update(html).digest("hex").slice(0, 12);
  cache = { html, uri: `ui://masterkey/run-viewer@${hash}` };
  return cache;
}

/** The content-hashed ui:// URI for the run viewer — shared by the resource and the tool's _meta.ui. */
export function getRunViewerUri(): string {
  return load().uri;
}

/**
 * The `_meta` to attach to a tool whose result should render in the run viewer. Mirrors the resourceUri
 * into BOTH the nested `ui.resourceUri` and the flat `ui/resourceUri` key (RESOURCE_URI_META_KEY) —
 * exactly what ext-apps `registerAppTool` does, for cross-host compatibility (some hosts read each).
 * Caller must gate on isMcpAppsEnabled().
 */
export function runViewerToolMeta(): Record<string, unknown> {
  const uri = getRunViewerUri();
  return { ui: { resourceUri: uri }, [RESOURCE_URI_META_KEY]: uri };
}

/**
 * Whether the connected client advertises MCP Apps support (negotiated at `initialize`). The robust
 * signal per the spec — NOT the client name. Used for the §4.4 gate inversion: an Apps-capable client
 * MUST keep `structuredContent` even if its name is on the legacy content-dropping list, because the
 * viewer renders from `structuredContent`. Returns false when the flag is off (no gate inversion then).
 *
 * ⚠️ SDK-VERSION CAVEAT (verified 2026-06-07): MCP Apps advertises capability under
 * `clientCapabilities.extensions["io.modelcontextprotocol/ui"]`, but our pinned `@modelcontextprotocol/sdk@1.26`
 * (hard-pinned by mcp-handler) uses a STRICT `ClientCapabilitiesSchema` (no `.passthrough()`), so it
 * STRIPS `extensions` on parse → `getClientCapabilities()` returns `{}` and this returns false for ALL
 * clients today. That's a safe no-op: the v1 hosts (claude.ai web, ChatGPT) are NOT on the
 * content-dropping list, so they keep `structuredContent` and render the viewer regardless. This detector
 * is correct + future-proof — it activates automatically once the SDK reaches 1.29+ (which adds
 * `extensions`). Until then, an apps-capable AND content-dropping client (e.g. VS Code) is the one gap.
 */
export function isClientAppsCapable(server: McpServer): boolean {
  if (!isMcpAppsEnabled()) return false;
  try {
    const cap = getUiCapability(server.server.getClientCapabilities());
    return !!cap?.mimeTypes?.includes(RESOURCE_MIME_TYPE);
  } catch {
    return false; // best-effort — never block a result on detection
  }
}

/** Register the run-viewer ui:// resource. Caller must gate on isMcpAppsEnabled(). */
export function registerRunViewerResource(server: McpServer): void {
  const { html, uri } = load();
  registerAppResource(
    server,
    "Masterkey Run Viewer",
    uri,
    { description: "Renders run_service / get_result media — images, video, audio, tables, and files." },
    async () => ({
      contents: [
        {
          uri,
          mimeType: RESOURCE_MIME_TYPE,
          text: html,
          _meta: {
            ui: {
              csp: {
                resourceDomains: [BLOB_ORIGIN], // Blob-mirrored media (images/video/audio/fonts/styles)
                connectDomains: [], // display-only v1 — no fetch/XHR/WebSocket/beacon from the iframe
              },
            },
          },
        },
      ],
    }),
  );
}
