// Masterkey — provider trust-tier tests (service-docs/TEAMS_AND_FIRST_PARTY.md).
//
// Run: npx tsx scripts/test/provider-tier.mts
// Money-free, network-free.
//
// What this guards: routing MUST be ordered by trust, not by price. Before 2026-07-29 the engine ranked
// on firstParty -> per-poll -> price, so a `*.vercel.app` proxy with no own domain could win a route
// purely by being a fraction of a cent cheaper than the provider on its own domain. Tier 4 is now demoted
// ahead of the price comparison.
//
// Also asserts the two orderings agree. `get_service` marks one backend `recommended:true`; if its
// display ranking diverged from what `run_service` actually picks, that flag would be a lie.
//
// NOT asserted: T2-vs-T3 ordering. That is an open owner decision (BACKLOG 4.6) and is deliberately
// unranked — the tier LABEL is informational for those two. Do not "fix" that without the owner.

import { backendTier } from "../../src/lib/mcp/tools";
import { TEAM_TIER, tierOf } from "../../src/data/team-tiers";
import { readFileSync } from "node:fs";

let passed = 0, failed = 0;
function ok(name: string, cond: boolean) {
  if (cond) passed++;
  else { failed++; console.error(`  ✗ ${name}`); }
}

// --- DOC FRESHNESS ------------------------------------------------------------------------------
// src/data/team-tiers.ts now RE-EXPORTS scripts/registry/teams.mjs, so routing and the pipeline cannot
// diverge. The remaining drift risk is the published doc: TEAMS_AND_FIRST_PARTY.md is generated by
// gen-teams-doc.mjs, so editing teams.mjs without regenerating leaves the doc lying about the grading.
{
  const doc = readFileSync("service-docs/TEAMS_AND_FIRST_PARTY.md", "utf8");
  const missing = Object.keys(TEAM_TIER).filter((team) => !doc.includes(team));
  ok(`every graded team appears in TEAMS_AND_FIRST_PARTY.md${missing.length ? ` (missing: ${missing.join(", ")})` : ""}`, missing.length === 0);
  // Tier counts stated in the doc headings must match the map, or the doc is stale.
  for (const [tier, n] of [[2, 5], [3, 7], [4, 4]] as [number, number][]) {
    const actual = Object.values(TEAM_TIER).filter((t) => t === tier).length;
    ok(`doc says Tier ${tier} has ${n} teams; map has ${actual}`, actual === n);
  }
}

// --- tier classification (per service-docs/TEAMS_AND_FIRST_PARTY.md) -----------------------------
ok("owner's own endpoint → T1", backendTier({ firstParty: true }) === "T1");
ok("BlockRun (direct relationship) → T2", backendTier({ team: "BlockRun" }) === "T2");
ok("Merit → T2", backendTier({ team: "Merit" }) === "T2");
// Regression: the handoff listed Heurist under T2, but TEAMS_AND_FIRST_PARTY.md grades it T3.
// The doc is generated from the live registry and wins.
ok("Heurist → T3 (NOT T2, despite the handoff)", backendTier({ team: "Heurist" }) === "T3");
ok("Xona (own domain, no relationship) → T3", backendTier({ team: "Xona" }) === "T3");
ok("untagged provider on own domain → T3", backendTier({}) === "T3");
ok("gg402 (graded proxy) → T4", backendTier({ team: "gg402" }) === "T4");
ok("untagged platform host → T4", backendTier({ hosting: "platform" }) === "T4");
// A graded team beats the hosting heuristic: TEAMS_AND_FIRST_PARTY.md lists blockrun's *.run.app host
// under BlockRun (T2), so a known operator on shared infra is still that operator.
ok("graded T2 team on a platform host → stays T2", backendTier({ team: "BlockRun", hosting: "platform" }) === "T2");
// First-party wins outright — it IS the owner, whatever they deploy on.
ok("first-party on a platform host → T1", backendTier({ firstParty: true, hosting: "platform" }) === "T1");

// --- the regression: trust must beat price ------------------------------------------------------
type B = { providerId: string; firstParty?: boolean; team?: string; hosting?: "custom" | "platform"; price?: { amount: number } };
const priceFloor = (b: B) => b.price?.amount ?? Infinity;
// Mirrors rankTargets / rankBackendsForDisplay: trust tier is the PRIMARY key, price only breaks ties.
const rank = (bs: B[]) => [...bs].sort((a, b) => tierOf(a) - tierOf(b) || priceFloor(a) - priceFloor(b));

const cheapProxy: B = { providerId: "proxy", hosting: "platform", price: { amount: 0.001 } };
const dearOwnDomain: B = { providerId: "real", team: "BlockRun", price: { amount: 0.005 } };
ok(
  "a cheaper T4 proxy does NOT beat a pricier own-domain provider",
  rank([cheapProxy, dearOwnDomain])[0].providerId === "real",
);

const firstParty: B = { providerId: "owner", firstParty: true, price: { amount: 9.99 } };
ok(
  "first-party still wins even when far more expensive",
  rank([cheapProxy, dearOwnDomain, firstParty])[0].providerId === "owner",
);

ok(
  "a cheaper T3 does NOT beat a pricier T2 (full ladder, not just T1/T4)",
  rank([
    { providerId: "t3", team: "Xona", price: { amount: 0.001 } },
    { providerId: "t2", team: "Sponge", price: { amount: 0.05 } },
  ])[0].providerId === "t2",
);

ok(
  "among two T4 proxies, cheapest still wins",
  rank([
    { providerId: "t4-dear", hosting: "platform", price: { amount: 0.9 } },
    { providerId: "t4-cheap", hosting: "platform", price: { amount: 0.1 } },
  ])[0].providerId === "t4-cheap",
);

ok(
  "T4 is a fallback, not an exclusion — it wins when it is the only option",
  rank([cheapProxy])[0].providerId === "proxy",
);

// A T4 with no price must not float to the top on an Infinity comparison.
ok(
  "unpriced T4 still ranks below a priced own-domain backend",
  rank([{ providerId: "t4-unpriced", hosting: "platform" }, dearOwnDomain])[0].providerId === "real",
);

// --- THE REAL-WORLD CASE: same service, several providers --------------------------------------
// "Exa provided by Exa" must beat "Exa provided by Merit/BlockRun" unless the caller pins one. These are
// three BACKENDS of the single `exa` service, so rankTargets picks between them — and T1 must win even
// though a T2 route could undercut it on price.
{
  const exa: B[] = [
    { providerId: "blockrun", team: "BlockRun", price: { amount: 0.012 } },
    { providerId: "stableenrich", team: "Merit", price: { amount: 0.010 } },
    { providerId: "exa", firstParty: true, price: { amount: 0.007 } },
  ];
  ok("Exa's own endpoint wins over Merit/BlockRun reselling Exa", rank(exa)[0].providerId === "exa");
  // …and still wins when it is the MOST expensive, which is the case price-ranking would get wrong.
  const dearer: B[] = [
    { providerId: "blockrun", team: "BlockRun", price: { amount: 0.001 } },
    { providerId: "exa", firstParty: true, price: { amount: 0.05 } },
  ];
  ok("first-party wins even when 50x pricier than a T2 reseller", rank(dearer)[0].providerId === "exa");
}

console.log(`\nprovider-tier tests: ${passed} passed, ${failed} failed.`);
process.exit(failed ? 1 : 0);
